=== vuhoangnam30699/T2301E_NAM/xml/school.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="https://www.w3schools1.com"
           xmlns="https://www.w3schools1.com"
           elementFormDefault="qualified">

    <xs:element name="schools">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="school" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="student" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="name" type="xs:string"/>
                                        <xs:element name="age" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== vuhoangnam30699/T2301E_NAM/xml/school.xml
<?xml version="1.0" encoding="UTF-8"?>

<schools
        xmlns="https://www.w3schools1.com"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="https://www.w3schools1.com/ school.xsd">
    <school>
        <student>
            <name>nam</name>
            <age>3</age>
        </student>

        <student>
            <name>vu</name>
            <age>2</age>
        </student>

        <student>
            <name>hoang</name>
            <age>5</age>
        </student>
    </school>

    <school>
        <student>
            <name>nam</name>
            <age>3</age>
        </student>

        <student>
            <name>vu</name>
            <age>2</age>
        </student>

        <student>
            <name>hoang</name>
            <age>5</age>
        </student>
    </school>
</schools>
